// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetWindowTitle(arg1) {
  return window['go']['window']['API']['SetWindowTitle'](arg1);
}

export function Startup(arg1) {
  return window['go']['window']['API']['Startup'](arg1);
}
