// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {net} from '../models';
import {context} from '../models';

export function GetAllConnections():Promise<Array<connections.Connection>>;

export function HandleConnection(arg1:net.Conn):Promise<void>;

export function SendCommand(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
