// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllConnections() {
  return window['go']['connections']['Service']['GetAllConnections']();
}

export function HandleConnection(arg1) {
  return window['go']['connections']['Service']['HandleConnection'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['connections']['Service']['SendCommand'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['connections']['Service']['Startup'](arg1);
}
