// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAllListeners():Promise<void>;

export function CloseListener(arg1:string,arg2:string):Promise<void>;

export function ListListeners():Promise<Array<string>>;

export function OpenListener(arg1:string,arg2:string):Promise<void>;
