// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAllListeners() {
  return window['go']['listener']['Service']['CloseAllListeners']();
}

export function CloseListener(arg1, arg2) {
  return window['go']['listener']['Service']['CloseListener'](arg1, arg2);
}

export function ListListeners() {
  return window['go']['listener']['Service']['ListListeners']();
}

export function OpenListener(arg1, arg2) {
  return window['go']['listener']['Service']['OpenListener'](arg1, arg2);
}
